http:
  host: "0.0.0.0"
  port: "8081"
  
  
destination:
  cities: "CLE, LAX, SFO, PDX, PDF, ALL"
  
  
american:
  rest:
    host: "training4-american-api.us-e1.cloudhub.io"
    port: "80"
    protocol: "HTTP"
    basePath: "/"
    responseTimeout: "10000"
    clientId: "d846d01ea59640108779eaaa532d00ca"
    clientSecret: "F7C5ecA48EBA449399b4B140416849B0"